### PR TITLE
Feature: Social Login

### PR DESCRIPTION
**Pull request by eddiechankaitai**
Here can write some detail...

### CODE REVIEW

**Review by eddiechankaitaiuk — COMMENTED** [review]
This line is good but it's better if you capitalize H.

**Review by eddiechankaitaiuk — CHANGES_REQUESTED** [review]
Please make these changes and do another push

**Review by eddiechankaitai — COMMENTED** [review]
2nd update request please.

**Review by eddiechankaitaiuk — CHANGES_REQUESTED** [review]
You have not completed your update. Some of them are still there.

**Review by eddiechankaitaiuk — APPROVED** [review]
Everything looks perfect. Let's go ahead with merging!

**Pull request merged**
